#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    li=list(s)
    l=0
    v=0
    for i in li:
        if(i=='U'):
            l=l+1
        if(i=='D'):
            l=l-1
        if(l==0 and i=='U'):
            v=v+1
    return v

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
