#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the repeatedString function below.
def repeatedString(s, n):
    c=0
    ch=0
    l=len(s)
    q=n//l
    r=n%l
    li=list(s)
    for i in li:
        if(i=='a'):
            ch=ch+1
    c=ch*q
    if(r!=0):
        for i in range(r):
            if(s[i]=='a'):
                c=c+1
    return c

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
